# Generated by Django 5.2.6 on 2026-01-30 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_productfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='productfaq',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
