# Generated by Django 5.2.6 on 2026-01-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_productfaq_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_products',
            field=models.ManyToManyField(blank=True, related_name='recommended_by', to='store.product'),
        ),
    ]
